development:
  adapter: postgresql
  database: renda_fixa_api_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: renda_fixa_api_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: renda_fixa_api_production
  pool: 5
  timeout: 5000
